# htpasswd -c auth k8s  # workshop
# kubectl create secret generic kuard-auth --from-file=auth --dry-run='client' -o yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuard.fullname" . }}-auth
data:
  auth: {{ .Values.authKey }}
